## ejemplo del libro
Ejemplo de la pagina 11

In [2]:
import numpy as np

In [3]:
a=np.array([[2, 4, 6, 18],[4, 5, 6, 24],[3, 1, -2, 4]])

In [4]:
a

array([[ 2,  4,  6, 18],
       [ 4,  5,  6, 24],
       [ 3,  1, -2,  4]])

In [5]:
a[0,:] = a[0,:]/2

In [6]:
a

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 24],
       [ 3,  1, -2,  4]])

In [7]:
a[1,:] = a[1,:] - (4 * a[0,:])
a[2,:] = a[2,:] - (3 * a[0,:])


In [8]:
a

array([[  1,   2,   3,   9],
       [  0,  -3,  -6, -12],
       [  0,  -5, -11, -23]])

In [9]:
a[1,:] = a[1,:] / 3

In [10]:
a


array([[  1,   2,   3,   9],
       [  0,  -1,  -2,  -4],
       [  0,  -5, -11, -23]])

In [11]:
a[1,:] = a[1,:] * (-1)

In [12]:
a

array([[  1,   2,   3,   9],
       [  0,   1,   2,   4],
       [  0,  -5, -11, -23]])

In [13]:
a[0,:] = a[0,:] - (2* a[1,:])
a[2,:] = a[2,:] - (5* a[1,:])


In [14]:
a

array([[  1,   0,  -1,   1],
       [  0,   1,   2,   4],
       [  0, -10, -21, -43]])

In [15]:
a[2,:] = a[2,:] + (10* a[1,:])

In [16]:
a

array([[ 1,  0, -1,  1],
       [ 0,  1,  2,  4],
       [ 0,  0, -1, -3]])

In [17]:
a[2,:] = a[2,:] * (-1)

In [18]:
a

array([[ 1,  0, -1,  1],
       [ 0,  1,  2,  4],
       [ 0,  0,  1,  3]])

In [20]:
a[0,:] = a[0,:] + a[2,:]
a[1,:] = a[1,:] - (2* a[2,:])

In [21]:
a

array([[ 1,  0,  1,  7],
       [ 0,  1,  0, -2],
       [ 0,  0,  1,  3]])

In [22]:
a[0,:] = a[0,:] - a[2,:]

In [23]:
a

array([[ 1,  0,  0,  4],
       [ 0,  1,  0, -2],
       [ 0,  0,  1,  3]])

In [1]:
import matplotlib.pyplot as plt